[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :4
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :5
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :6
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :7
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :8
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :9
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :10
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :11
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :210
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :214
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :213
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :212
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :211
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :209
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :208
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :207
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :197
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :198
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :199
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :200
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :201
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :202
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :203
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :204
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :205
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :206
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :196
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :195
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :194
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :190
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :191
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :192
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :193
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :187
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :188
[E 20180416 17:30:58 j_filter:70] error:no sn and no mac,id is :189
[I 20180416 17:30:58 j_filter:84] Inset data into table ConnectionInfo sucess!
[W 20181202 20:21:03 base:170] Not Found: /favicon.ico
[E 20181202 20:22:36 base:256] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjun/Desktop/coding-160/apps/detail/views.py", line 25, in index
    return render(request, 'detail/index.html', context)
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'endif'
[E 20181202 20:22:39 base:256] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjun/Desktop/coding-160/apps/detail/views.py", line 25, in index
    return render(request, 'detail/index.html', context)
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'endif'
[E 20181202 20:24:51 base:256] Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjun/Desktop/coding-160/apps/detail/views.py", line 25, in index
    return render(request, 'detail/index.html', context)
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'endif'
